# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    projects: 'aspnetcore/tutorials/first-web-api/samples/3.0/TodoApi/*.csproj'
    feedsToUse: 'select'
    vstsFeed: 'ebc9d3c9-3ac8-4241-a13a-1543acc8b0ab'
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: 'aspnetcore/tutorials/first-web-api/samples/3.0/TodoApi/*.csproj'
